ARG NODE_VERSION=20.12.2

FROM node:${NODE_VERSION}-slim as base

ARG PORT=9001

ENV NODE_ENV=production

WORKDIR /usr/src/app

# Install Python and other dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set Python environment variables if needed
ENV PYTHON python3
ENV PYTHON_PATH /usr/bin/python3

# Build
FROM base as build

# Copy the package.json
COPY ./package.json /usr/src/app/dist/package.json

COPY . .

RUN npm install -g node-gyp@10.1.0 -g @abandonware/bluetooth-hci-socket@0.5.3-12
# Run
FROM base

ENV PORT=$PORT

COPY ./dist /usr/src/app/dist

# Install node-gyp and @abandonware/bluetooth-hci-socket


CMD [ "node", "dist/main.js" ]