# This is a basic workflow to help you get started with Actions

name: Build and Run Panorama App

on:
  # Triggers t
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Run serve
        run: npm serve
