# This is a basic workflow to help you get started with Actions

name: Run UnitTests

on:
  # Triggers t
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]


jobs:
  build-linux:
    name: build on ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
  
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 14.16.X
          
      - name: Install Dependencies
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Run Jest
        run: npm run test:unit
        
